### ISSUE TITLE
Incorrect wrapping of pure functions

### ISSUE THREAD

**Issue by kolmodin** [haskell/c2hs#130] opened 2015-03-26 15:52 UTC
Here's a C function;

```c
// my_add.h
void my_add(int *a, int *b, int *result);
```

```c
// my_add.c
#include "my_add.h"

void my_add(int *a, int *b, int *result) {
  *result = *a + *b;
}
```
You could argue that it's pure, since it reads nothing but the the arguments and then stores the result in the out param.

I write this Haskell program;

```haskell
-- myadd.chs
module Main where

import Foreign.C.Types
import Foreign.Ptr
import Foreign.Storable
import Foreign.Marshal.Alloc
import Foreign.Marshal.Utils

import System.IO.Unsafe(unsafePerformIO)

#include "my_add.h"

main = do
  print (myAdd 1 2)
  print =<< myAddIO 1 2

{#fun pure unsafe my_add as myAdd   {`CInt', `CInt', alloca- `CInt' peek* } -> `()'#}
{#fun      unsafe my_add as myAddIO {`CInt', `CInt', alloca- `CInt' peek* } -> `()'#}
```

I've wrapped my_add twice, once as a pure function and once in IO.
Running this function I'd expect that it'd write two lines with the number 3. Alas it does not.

```bash
 $ clang -c my_add.c
 $ c2hs myadd.chs
 $ ghc --make myadd.hs my_add.o
 $ ./myadd
0
3
```

Why? Let's have a look at the generated .hs file. (The issue remains even with newer versions of c2hs).

```haskell
-- GENERATED by C->Haskell Compiler, version 0.16.4 Crystal Seed, 24 Jan 2009 (Haskell)
-- Edit the ORIGNAL .chs file instead!


{-# LINE 1 "myadd.chs" #-}module Main where

import Foreign.C.Types
import Foreign.Ptr
import Foreign.Storable
import Foreign.Marshal.Alloc
import Foreign.Marshal.Utils

import System.IO.Unsafe(unsafePerformIO)


main = do
  print (myAdd 1 2)
  print =<< myAddIO 1 2

myAdd :: CInt -> CInt -> CInt
myAdd a1 a2 =
  unsafePerformIO $
  with a1 $ \a1' -> 
  with a2 $ \a2' -> 
  alloca $ \a3' -> 
  let {res = myAdd'_ a1' a2' a3'} in
  peek  a3'>>= \a3'' -> 
  return (a3'')
{-# LINE 17 "myadd.chs" #-}
myAddIO :: CInt -> CInt -> IO (CInt)
myAddIO a1 a2 =
  with a1 $ \a1' -> 
  with a2 $ \a2' -> 
  alloca $ \a3' -> 
  myAddIO'_ a1' a2' a3' >>= \res ->
  peek  a3'>>= \a3'' -> 
  return (a3'')
{-# LINE 18 "myadd.chs" #-}

foreign import ccall unsafe "myadd.chs.h my_add"
  myAdd'_ :: ((Ptr CInt) -> ((Ptr CInt) -> ((Ptr CInt) -> ())))

foreign import ccall unsafe "myadd.chs.h my_add"
  myAddIO'_ :: ((Ptr CInt) -> ((Ptr CInt) -> ((Ptr CInt) -> (IO ()))))

```

We see that `myAdd` does a let-binding, but never uses the `res` variable. It simply won't execute the function.
To fix this, either `myAdd'_` should be in IO like in `myAddIO'_`, or `res` must be forced.
Changing
```let {res = myAdd'_ a1' a2' a3'} in```
to
```let {res = myAdd'_ a1' a2' a3'} in res `seq````
fixes the issue (though requires that seq has been imported - which is true for all modules that imports the Prelude).

**Comment by ian-ross** [comment] 2015-03-26 16:05
Ha.  Good one.  I'd dispute that `my_add` is really "pure" (whatever that actually means here!), because 1). it does the addition as a side effect, and 2). it has a return type of `void` and any pure Haskell function returning `()` doesn't need to do anything to make a `()` value.  As you say, you can force the computation using `seq`, but is that still "pure"?

Still, let me think about this, because it's a bit weird!

Maybe the solution is to always generate Haskell code in `IO` when you have a `pure` function hook for a C function of return type `void`?  (Since that's probably the best way to force the C function to be called.)

**Comment by kolmodin** [comment] 2015-03-26 18:41
`my_add` is pure because;
 - it only uses its given arguments as input
 - it will always return the same result for the same arguments
 - it does not change any external state
 - it's a common convention to use out arguments so writing to *result is just returning the value, and it unconditionally writes the value there. whether it returns the value with `return` or writes it to an out param is not important as the out param is exclusively reserved for the result of the function.

I'd argue that it's not less pure than `my_add = (+)`.

Doing special casing whether it's `void` or not will not work. Example;
```c
int my_add(int *a, int *b, int *result) {
  *result = *a + *b;
  return *result;
}
```

c2hs
```haskell
{#fun pure unsafe my_add2 as myAddBroken {`CInt', `CInt', alloca- `CInt` peek*} -> {`CInt'} id#}
```

haskell
```
myAdd2 :: CInt -> CInt -> (CInt, CInt)
myAdd2 a1 a2 = unsafePerformIO $
  with a1 $ \a1' ->
  with a2 $ \a2' ->
  alloca $ \a3' ->
  let {res = myAdd2'_ a1' a2' a3'} in
  peek a3'>>= \a3'' ->
  let {res' = id res} in return (res', a3'')
```

See how `peek` reads `a3'` before `res` has been forced (indeed, `res` doesn't get forced at all here).
In the tuple, the second value will always be garbage.

Likewise, a C function with the signature;
```c
int my_add3(int *a, int *b, int *result);
```
and wrapped like;
```haskell
{#fun pure unsafe my_add3 as myAddAlsoBroken {`CInt', `CInt', alloca- `CInt` peek*} -> {`CInt'} id #}
```
will return a tuple, and the second value will only be correct if the first value is evaluated first. We cannot make this assumption.

To fix this issue we have a choice;
 1. Change the `foreign import` signatures to IO and break user code that depended on the generated `foreign import`s.
 2. Use `seq` and break user code that doesn't import the Prelude.

I don't know how common (1) but I would think it's pretty rare. Though (2) should be rare as well.

**Comment by ian-ross** [comment] 2015-03-27 09:55
OK, I can see the arguments for calling this "pure".  That definitely makes sense.  However, I'm strongly resistant to changing the existing semantics of `fun` bindings in either of the ways that you propose.  C2HS is pretty widely used and it's just not practical to track down every package on Hackage or GitHub that uses it to check for breakages from a change like this.

I don't know what the original intention of the `pure` keyword in C2HS was (it was introduced after the original C2HS paper), but I think that it probably has to be interpreted as including the restriction "returns a single result via the C return value" -- at least that's what it looks like from the code that's generated.  I'd be interested to know what @mchakravarty has to say about this, because, apart from being very wary of changing the semantics of `fun` hooks in this way, I don't really have a good feeling for what's the right approach to take.

**Comment by mchakravarty** [comment] 2015-04-16 00:55
Sorry for being slow to respond.

The `pure` keyword is really about the signature of the generated binding — i.e., the result type is not in `IO`. So, I agree with @kolmodin that this is a bug (and a scenario that I simply forgot to take into account when doing the original implementation). The right fix IMHO is Choice 1 — that is to change the foreign import. (That is what I would write manually in this situation.)

I might not have stated it anywhere (my bad!), but my intention was always that the generated foreign declarations for `fun` bindings are an implementation detail that user code should not rely on. So, I don't see a problem in changing them, but it would make sense to bump the version number of c2hs in the same way as for an API change just in case somebody did rely on the internals.

**Comment by ian-ross** [comment] 2015-04-16 05:48
@mchakravarty  Thanks for the guidance!  I'll try to fix this this weekend.

**Comment by kolmodin** [comment] 2015-04-18 10:59
Thanks @mchakravarty and @ian-ross! :+1:

**Comment by ian-ross** [comment] 2015-04-19 20:23
@kolmodin I believe this is now fixed -- I used your `seq` approach.  I'm running regression tests now, but the test suite is fine, so I'm hopeful this will be OK.

**Comment by kolmodin** [comment] 2015-04-20 09:35
@ian-ross Was fix (2) easier than fix (1) @mchakravarty recommended?

**Comment by ian-ross** [comment] 2015-04-20 10:09
@kolmodin It was, since I'm not sure I understand what (1) was really proposing!  (And I also forgot the details of this discussion and relied on my notes to decide how to do the fix...)  Is the intention that the `pure` keyword should solely determine the result type of the final Haskell binding, but that all `foreign import` declarations should have a result type in `IO` to force invocation of the C function in the appropriate place?  If that's the case, that wouldn't be hard to do.  Otherwise, if the intention is that some `foreign import` declarations have result types in `IO` and some not, what's the mechanism for determining which approach to take in each case?

(By the way, I'm quite happy to go back and change this in line with Manuel's suggestion.  I probably went at it too quickly yesterday, trying to get something working before the end of the weekend...)

**Comment by kolmodin** [comment] 2015-04-21 12:27
(1) was proposing to change so that all foreign imports that c2hs ever generates are IO.
Irregardless whether a `#fun` is marked as `pure` or not, it should be in IO.

Indeed, `pure` would only mean that the generated Haskell binding would be pure, not the foreign import (which Manuel pointed out are an implementation detail and should not be relied on).

**Comment by ian-ross** [comment] 2015-04-21 20:05
@kolmodin OK, that's completely clear now.  Thanks for the explanation.  I'll try making things work that way and see what happens to the packages I have in my regression suite.  If nothing breaks, this does seem like a better way to go.  If some existing packages break because of dependencies on the exact form of the foreign imports, I'll have a think about what to do.

More in a few days when I've had a chance to do this.

**Comment by kolmodin** [comment] 2015-04-21 21:09
Two things Manuel said that we could do;
 - If it's not clear already from the documentation, document that the generated foreign imports are an implementation detail and that you're not supposed to rely on them.
 - Even if none of the packages in the regression suite breaks, bump the version to indicate the API change.

**Comment by ian-ross** [comment] 2015-04-24 15:22
@kolmodin  OK, I think this is going to work, apart from one thing.

Changing over to making all foreign imports have results in `IO` means that all C2HS pure calls need to use `unsafePerformIO`.  That's not a problem and is already used in some cases, but now it will be much more widespread, which means that code that doesn't import `unsafePerformIO` will break.  I've been meaning to fix an annoying feature of C2HS for a while, which is that it makes use of all sorts of standard library functions without managing the imports of those things for you.  That means that you basically have to write your CHS file, try compiling it then add any Haskell imports (`Foreign.C.Types`, etc.) and retry until you've got them all.  A better approach would be for C2HS to keep track of the functions it uses and to add appropriate imports to the generate Haskell code.

You can see where this is going.  I'll finish up the changes to deal with this problem on a branch, using the `IO` foreign imports, then I'll sort out this library imports stuff (issue #136).  Then everything should hopefully work without problems when I merge the branch.

I'll let you know when it's done.

**Comment by kolmodin** [comment] 2015-04-24 21:37
Ah, right. Automatic imports would be really nice. Thanks for working on this!

**Closed** 2015-06-22 17:46 UTC
