### ISSUE TITLE
Relax variadic function restrictions

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/c2hs#102] opened 2014-08-19 19:16 UTC
While the Haskell FFI cannot create a foreign declaration to a variadic function that will accept an arbitrary number of arguments, it is possible to create a foreign declaration with a fixed number of arguments. For example, the C function `int ioctl(int d, int request, ...)` can used in Haskell by forcing to have a specific type signature:

```haskell
{-# LANGUAGE ForeignFunctionInterface #-}
module Main where

import Foreign
import Foreign.C.Types

foreign import ccall "ioctl" c_ioctl :: CInt -> CInt -> Ptr () -> IO CInt
```

However, one cannot do this with `c2hs`, as it rejects all variadic functions. For example, this code:

```haskell
{-# LANGUAGE ForeignFunctionInterface #-}
module Main where

import Foreign
import Foreign.C.Types

#include <sys/ioctl.h>

{#fun unsafe ioctl as c_ioctl
  {    `Int'
  ,    `Int'
  ,    `Ptr ()'
  } -> `Int' #}
```

will be rejected with the error:

```
./Main.chs:9: (column 3) [ERROR]  >>> Variadic function!
  Calling variadic functions is not supported by the FFI; the function
  is defined at ("/usr/include/sys/ioctl.h": line 41).
```

Would there be any issues with relaxing `c2hs`'s restrictions on variadic functions to allow `#fun` bindings?

**Comment by ian-ross** [comment] 2015-01-24 13:40
@RyanGlScott I've done something for this, although it's a little restricted.  You can now do this:

``` c2hs
module Main where

import Foreign.Ptr
import Foreign.C.Types
import Foreign.C.String

#include <stdio.h>

{#fun variadic printf(int) as printi {`String', `Int'} -> `()'#}
{#fun variadic printf(int, int) as printi2 {`String', `Int', `Int'} -> `()'#}

main :: IO ()
main = do
  printi "TST 1: %d\n" 1234
  printi2 "TST 2: %d %d\n" 13 47
```

You need to mark the `fun` hook as `variadic` and you need to write the C types of the extra `va_args` parameters you're going to pass in parentheses after the C function name.

It's not pretty, and at the moment you can only use simple C types as the additional parameters.  If you want more or have problems with it as it stands, raise a ticket.  I'm not completely convinced about what I've done, so consider this just a first attempt!

**Comment by RyanGlScott** [comment] 2015-01-24 19:14
Awesome, thanks! Could you update [this wiki article](https://github.com/haskell/c2hs/wiki/Implementation-of-Haskell-Binding-Modules) to include the changes to the grammar? It's not clear to me how `variadic` interacts with `unsafe`, `pure`, and other keywords.

Also, I assume that "simple C types" does not encompass pointers? If so, then I can't use `ioctl` (my motivation for submitting this bug).

**Comment by ian-ross** [comment] 2015-01-25 08:30
@RyanGlScott That's right about "simple types" not yet covering pointers.  Consider this an experimental feature for the moment.  I did a slightly shoddy job for the first implementation as I'm still figuring out what the best way to deal with this is in the more general case.

The problem is that you need to know the C types for the `va_args` arguments you're going to pass, and that information isn't available from the C header file defining the variadic function, so it needs to go into the CHS file somehow.  The problem is that this is the *only* case where unadorned C code appears in the CHS file, so until now things haven't been set up to allow the CHS file parser to deal with this.  And that's slightly tricky, since you need to parse the C code defining the parameter types in a context where all the names defined in whatever included C header files are in scope.

I have some ideas of how to do this, hopefully in a way that should "just work" for all variations on the parameter types, but I wanted to do a slightly dumb implementation first so that I could sort out all the other parts that are needed before focusing on this C parameter type parsing problem.

I will reopen this issue and will have a go at a definitive solution later in the week.  Oh, and I'll fix the documentation tomorrow.

**Comment by ian-ross** [comment] 2015-02-06 15:02
@RyanGlScott OK, I've done something for this.  I think it's a pretty good solution, but you should have a look and tell me what you think.  The test case for issue #102 shows how to use this, including some playing with `fcntl` that should be relatively similar to what you want to do with `ioctl`.  You can use more or less any C type in the variadic function definitions now (so long as the types don't contain commas -- if you want funny function pointer types, you'll need to define a `typedef` for them in a C header file).  The syntax has changed a little (you need to put the variadic argument types in square brackets rather than parentheses: parentheses were getting a bit syntactically overloaded...), but otherwise it works the same as it did before.

I'm going to close this issue now (again), since I think this is a *reasonably* definitive approach to this use case.  If I'm wrong about that, let me know and we can revisit it.

**Closed by ian-ross** 2015-02-06 15:02 UTC
Labels: enhancement

**Comment by RyanGlScott** [comment] 2015-02-06 17:41
This is seriously cool, thanks! I can now do all the crazy `printf`ing and `ioctl`ing that I want using `c2hs`. (Well, *almost* all of the `ioctl`ing, since I can't use `Ptr ()` as an argument, but that's due to a [separate issue](https://github.com/haskell/c2hs/issues/83#issuecomment-73280009).)

**Comment by ian-ross** [comment] 2015-02-06 17:48
@RyanGlScott Yeah, I'll fix that other thing.  It just fell through the gaps.  If you can think of anything else to do on this variadic stuff, I'd be interested to hear.
