### ISSUE TITLE
struct typedef handling broke recently (libssh2 bindings do not compile)

### ISSUE THREAD

**Issue by trofi** [haskell/c2hs#152] opened 2015-11-05 21:33 UTC
libssh2 fails to compile as:
```
include/libssh2_local.h:6: (column 1) [ERROR]  >>> Illegal use of incomplete type!
  Expected a fully defined structure or union tag; instead found incomplete type.
```

Trimmed down example looks like:
```c
// a.h
struct a { int f; };

typedef struct a s_a;
```
```haskell
-- a.chs
module M where

f = {# sizeof a #}
g = {# sizeof s_a #}
```

Fails as:
```
$ c2hs a.h a.chs 
c2hs: Errors during expansion of binding hooks:

a.h:3: (column 1) [ERROR]  >>> Illegal use of incomplete type!
  Expected a fully defined structure or union tag; instead found incomplete type.
```

**Comment by ian-ross** [comment] 2015-11-06 09:00
@trofi OK, this is a regression caused by the fix to #141. I'll take a look after the weekend.

**Comment by mrkkrp** [comment] 2015-11-24 17:03
Any progress on this?

**Comment by ian-ross** [comment] 2015-11-24 17:05
No.  Started a new job recently, zero time to work on C2HS.  PRs more than welcome...

**Comment by ian-ross** [comment] 2015-11-29 17:21
This now appears to be fixed in HEAD (I can build `libssh2` with it anyway).  I'll do a release either later today or in the next couple of days, depending on how another bug fix I'm doing goes.

**Closed by ian-ross** 2015-11-29 17:21 UTC

**Comment by kaoskorobase** [comment] 2015-11-30 10:47
Cool, thanks!
