### ISSUE TITLE
Can't build cpthyon on Macos Sierra

### ISSUE THREAD

**Issue by JulianZhang** [haskell/c2hs#178] opened 2016-12-22 02:22 UTC
My system is Macos Sierra, When I build cpython I get error as blow.

--  While building package cpython-3.4.0 using:
      ~/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.5.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: ./.stack-work/logs/cpython-3.4.0.log

    Configuring cpython-3.4.0...
    Building cpython-3.4.0...
    Preprocessing library cpython-3.4.0...
    c2hs: C header contains errors:

    /usr/include/stdio.h:133: (column 19) [ERROR]  >>> Syntax error !
      The symbol `_close' does not fit here.

**Comment by mchakravarty** [comment] 2016-12-22 02:41
This is a duplicate of #176.

**Closed** 2017-03-06 20:14 UTC
Labels: duplicate
