### ISSUE TITLE
The identifier `flock' needs to be a C type name on OS X

### ISSUE THREAD

**Issue by maoe** [haskell/c2hs#134] opened 2015-04-11 15:00 UTC
c2hs fails to process [this snippet](https://gist.github.com/maoe/8b46856aa06c3a7574ab#file-flock-chs). The trace output is attached in the same gist.

The same snippet just works fine on Linux.

* OS X Yosemite 10.10.3
* c2hs 0.22.1

**Comment by ian-ross** [comment] 2015-04-13 19:19
@maoe Thanks for the report!  I'll take a look some time in the next few days.

**Comment by ian-ross** [comment] 2015-06-03 14:58
@maoe Could you let me know if you still have this problem with the most recent of C2HS on Hackage (0.25.2)?  I see that rhe version you're using (0.22.1) is about six months old, and I've done some work on structure tags/type names since then.  Thanks!

**Comment by maoe** [comment] 2015-06-04 11:01
I got exactly the same error with c2hs 0.25.2 and ghc 7.10.1.

**Comment by ian-ross** [comment] 2015-06-05 11:38
@maoe OK, thanks for checking!  I'll investigate what's going on.

**Comment by ian-ross** [comment] 2015-06-24 16:27
OK, I've figured out why this is happening.  Not sure how to fix it yet...  It's definitely a bug.

The problem is that on OS X, `fcntl.h` defines both `struct flock` and the `flock` function in the same header file.  This is causing C2HS to get confused about what `flock` really refers to.  The problem doesn't arise on Linux because the `flock` structure is defined in a seperate header file, which somehow means C2HS doesn't get confused.

Anyway, I now have a Linux test case I can use to fix this so I should be able to work out what the problem is.

**Comment by ian-ross** [comment] 2015-06-25 18:04
@maoe I believe this is now fixed in the GitHub HEAD version.  I've checked my Linux test case and a limited test on OS X.  I'll release a new version to Hackage in a week or two (there are some other potentially breaking changes in this version that I want to give people a chance to play with before releasing).

**Closed by ian-ross** 2015-06-25 18:04 UTC
Labels: bug, macos
